# Generated by Django 4.2.2 on 2023-06-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextToSpeech',
            new_name='TextToSpeechModels',
        ),
    ]
