# Generated by Django 4.2.2 on 2023-06-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0003_alter_texttospeechmodels_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttospeechmodels',
            name='audio',
            field=models.URLField(blank=True),
        ),
    ]
