# Generated by Django 4.2.2 on 2023-06-30 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0007_alter_texttospeechmodels_render'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttospeechmodels',
            name='render',
        ),
    ]
