# Generated by Django 4.2.2 on 2023-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0010_speechtotextmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtotextmodels',
            name='audio',
            field=models.TextField(),
        ),
    ]
