# Generated by Django 4.2.4 on 2023-08-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0011_alter_speechtotextmodels_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtotextmodels',
            name='audio',
            field=models.FileField(upload_to='musics'),
        ),
    ]
